name: iOS Lint

on:
  push:
    branches:
      - main
    paths:
      - 'ios/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ios/**'

jobs:
  swiftlint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: |
        cd ios
        swiftlint --reporter github-actions-logging